### ISSUE TITLE
顯示動畫瘋封面 & 視覺圖 - 已失效？

### ISSUE THREAD

**Issue by NiGHTsC** [zica87/self-made-userscipts#1]
請問這腳本是否已失效？

謝謝。

**Comment by zica87** [comment]
剛用無痕模式試了一下有正常顯示封面，只有換集的時候不會運作，這個我剛查了一下應該修得好。

除此之外有遇到其他問題嗎？

**Comment by NiGHTsC** [comment]
哦？還是是我這邊環境的問題？無痕/登入的情況下都是這樣。
啊，對了，換集的時候也確實不會運作，需要再重整一次。
Chrome 123.0.6312.59（64位元）
![未命名](https://github.com/zica87/self-made-userscipts/assets/16272968/3c692fb6-eae2-4fb6-b3eb-1f8f0d6d4b38)

**Comment by zica87** [comment]
換集後／部分作品不會顯示封面的問題應該修好了
如果還有問題再回報

謝謝
